name: ngd_datatable_demo
description: DEMO page of ngd_datatable
version: 0.1.0
# homepage: https://icemanbsi.github.io

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^7.0.2
  angular_router: ^3.0.1
  ngd_datatable:
    path: ..

dev_dependencies:
  angular_test: ^4.0.1
  build_runner: ^2.1.5
  build_test: ^2.1.4
  build_web_compilers: ^3.2.1
  pedantic: ^1.8.0
  test: ^1.6.0
