name: ngd_datatable
description: This plugin is made to display a data table on Angular Dart platform. Currently it support a simple data table with or without server processing.
version: 0.1.10+1
homepage: https://icemanbsi.github.io/ngd-datatable/

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^7.0.2
  angular_components:
    git: 
      url: https://github.com/angulardart-community/angular_components.git
      path: angular_components
  angular_router: ^3.0.1

dev_dependencies:
  angular_test: ^4.0.1
  build_runner: ^2.1.5
  build_test: ^2.1.4
  build_web_compilers: ^3.2.1
  pedantic: ^1.8.0
  test: ^1.6.0
